# version: '3.8'

services:
  frontend:
    image: ihirokicom-client-image  # イメージ名を指定
    container_name: ihirokicom-client  # コンテナ名を指定
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - web-app-network
    # depends_on:
    #   - backend
    tty: true
  
  # バックエンド未開発なので
  # backend:
  #   image: ihirokicom-server-image  # イメージ名を指定
  #   ihirokicom: temp-server  # コンテナ名を指定
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3001:3000"
  #   volumes:
  #     - ./server:/server
  #   networks:
  #     - web-app-network
  #   tty: true

networks:
  web-app-network:
    driver: bridge
